export const RDO_LIST = [
  "Revenue District Office No. 001 - Laoag City, Ilocos Norte",
  "Revenue District Office No. 002 - Vigan, Ilocos Sur",
  "Revenue District Office No. 003 - San Fernando, La Union",
  "Revenue District Office No. 004 - Calasiao, West Pangasinan",
  "Revenue District Office No. 005 - Alaminos, Pangasinan",
  "Revenue District Office No. 006 - Urdaneta, Pangasinan",
  "Revenue District Office No. 007 - Bangued, Abra",
  "Revenue District Office No. 008 - Baguio City",
  "Revenue District Office No. 009 - La Trinidad, Benguet",
  "Revenue District Office No. 010 - Bontoc, Mt. Province",
  "Revenue District Office No. 011 - Tabuk City, Kalinga",
  "Revenue District Office No. 012 - Lagawe, Ifugao",
  "Revenue District Office No. 013 - Tuguegarao, Cagayan",
  "Revenue District Office No. 014 - Bayombong, Nueva Vizcaya",
  "Revenue District Office No. 015 - Naguilian, Isabela",
  "Revenue District Office No. 016 - Cabarroguis, Quirino",
  "Revenue District Office No. 17A - Tarlac City, Tarlac",
  "Revenue District Office No. 17B - Paniqui, Tarlac",
  "Revenue District Office No. 018 - Olongapo City",
  "Revenue District Office No. 019 - Subic Bay Freeport Zone",
  "Revenue District Office No. 020 - Balanga, Bataan",
  "Revenue District Office No. 21A - North Pampanga",
  "Revenue District Office No. 21B - South Pampanga",
  "Revenue District Office No. 21C - Clark Freeport Zone",
  "Revenue District Office No. 022 - Baler, Aurora",
  "Revenue District Office No. 23A - North Nueva Ecija",
  "Revenue District Office No. 23B - South Nueva Ecija",
  "Revenue District Office No. 024 - Valenzuela City",
  "Revenue District Office No. 25A (now RDO West Bulacan) - Plaridel, Bulacan",
  "Revenue District Office No. 25B (now RDO East Bulacan) - Sta. Maria, Bulacan",
  "Revenue District Office No. 026 - Malabon-Navotas",
  "Revenue District Office No. 027 - Caloocan City",
  "Revenue District Office No. 028 - Novaliches",
  "Revenue District Office No. 029 - Tondo – San Nicolas",
  "Revenue District Office No. 030 - Binondo",
  "Revenue District Office No. 031 - Sta. Cruz",
  "Revenue District Office No. 032 - Quiapo-Sampaloc-San Miguel-Sta. Mesa",
  "Revenue District Office No. 033 - Intramuros-Ermita-Malate",
  "Revenue District Office No. 034 - Paco-Pandacan-Sta. Ana-San Andres",
  "Revenue District Office No. 035 - Romblon",
  "Revenue District Office No. 036 - Puerto Princesa",
  "Revenue District Office No. 037 - San Jose, Occidental Mindoro",
  "Revenue District Office No. 038 - North Quezon City",
  "Revenue District Office No. 039 - South Quezon City",
  "Revenue District Office No. 040 - Cubao",
  "Revenue District Office No. 041 - Mandaluyong City",
  "Revenue District Office No. 042 - San Juan",
  "Revenue District Office No. 043 - Pasig",
  "Revenue District Office No. 044 - Taguig-Pateros",
  "Revenue District Office No. 045 - Marikina",
  "Revenue District Office No. 046 - Cainta-Taytay",
  "Revenue District Office No. 047 - East Makati",
  "Revenue District Office No. 048 - West Makati",
  "Revenue District Office No. 049 - North Makati",
  "Revenue District Office No. 050 - South Makati",
  "Revenue District Office No. 051 - Pasay City",
  "Revenue District Office No. 052 - Parañaque",
  "Revenue District Office No. 53A - Las Piñas City",
  "Revenue District Office No. 53B - Muntinlupa City",
  "Revenue District Office No. 54A - Trece Martirez City, East Cavite",
  "Revenue District Office No. 54B - Kawit, West Cavite",
  "Revenue District Office No. 055 - San Pablo City",
  "Revenue District Office No. 056 - Calamba, Laguna",
  "Revenue District Office No. 057 - Biñan, Laguna",
  "Revenue District Office No. 058 - Batangas City",
  "Revenue District Office No. 059 - Lipa City",
  "Revenue District Office No. 060 - Lucena City",
  "Revenue District Office No. 061 - Gumaca, Quezon",
  "Revenue District Office No. 062 - Boac, Marinduque",
  "Revenue District Office No. 063 - Calapan, Oriental Mindoro",
  "Revenue District Office No. 064 - Talisay, Camarines Norte",
  "Revenue District Office No. 065 - Naga City",
  "Revenue District Office No. 066 - Iriga City",
  "Revenue District Office No. 067 - Legazpi City, Albay",
  "Revenue District Office No. 068 - Sorsogon, Sorsogon",
  "Revenue District Office No. 069 - Virac, Catanduanes",
  "Revenue District Office No. 070 - Masbate, Masbate",
  "Revenue District Office No. 071 - Kalibo, Aklan",
  "Revenue District Office No. 072 - Roxas City",
  "Revenue District Office No. 073 - San Jose, Antique",
  "Revenue District Office No. 074 - Iloilo City",
  "Revenue District Office No. 075 - Zarraga, Iloilo City",
  "Revenue District Office No. 076 - Victorias City, Negros Occidental",
  "Revenue District Office No. 077 - Bacolod City",
  "Revenue District Office No. 078 - Binalbagan, Negros Occidental",
  "Revenue District Office No. 079 - Dumaguete City",
  "Revenue District Office No. 080 - Mandaue City",
  "Revenue District Office No. 081 - Cebu City North",
  "Revenue District Office No. 082 - Cebu City South",
  "Revenue District Office No. 083 - Talisay City, Cebu",
  "Revenue District Office No. 084 - Tagbilaran City",
  "Revenue District Office No. 085 - Catarman, Northern Samar",
  "Revenue District Office No. 086 - Borongan, Eastern Samar",
  "Revenue District Office No. 087 - Calbayog City, Samar",
  "Revenue District Office No. 088 - Tacloban City",
  "Revenue District Office No. 089 - Ormoc City",
  "Revenue District Office No. 090 - Maasin, Southern Leyte",
  "Revenue District Office No. 091 - Dipolog City",
  "Revenue District Office No. 092 - Pagadian City, Zamboanga del Sur",
  "Revenue District Office No. 093A - Zamboanga City, Zamboanga del Sur",
  "Revenue District Office No. 093B - Ipil, Zamboanga Sibugay",
  "Revenue District Office No. 094 - Isabela, Basilan",
  "Revenue District Office No. 095 - Jolo, Sulu",
  "Revenue District Office No. 096 - Bongao, Tawi-Tawi",
  "Revenue District Office No. 097 - Gingoog City",
  "Revenue District Office No. 098 - Cagayan de Oro City",
  "Revenue District Office No. 099 - Malaybalay City, Bukidnon",
  "Revenue District Office No. 100 - Ozamis City",
  "Revenue District Office No. 101 - Iligan City",
  "Revenue District Office No. 102 - Marawi City",
  "Revenue District Office No. 103 - Butuan City",
  "Revenue District Office No. 104 - Bayugan City, Agusan del Sur",
  "Revenue District Office No. 105 - Surigao City",
  "Revenue District Office No. 106 - Tandag, Surigao del Sur",
  "Revenue District Office No. 107 - Cotabato City",
  "Revenue District Office No. 108 - Kidapawan, North Cotabato",
  "Revenue District Office No. 109 - Tacurong, Sultan Kudarat",
  "Revenue District Office No. 110 - General Santos City",
  "Revenue District Office No. 111 - Koronadal City, South Cotabato",
  "Revenue District Office No. 112 - Tagum, Davao del Norte",
  "Revenue District Office No. 113A - West Davao City",
  "Revenue District Office No. 113B - East Davao City",
  "Revenue District Office No. 114 - Mati, Davao Oriental",
  "Others"
];

export const BIR_PURPOSES = [
  { key: "Update of COR", text: "To sign, submit, receive, fill out necessary documents for the update of Certificate of Registration (COR) with the Bureau of Internal Revenue (BIR)" },
  { key: "Process COR Update", text: "To apply for, request, transact, and/or otherwise process the update of Certificate of Registration (COR) with the Bureau of Internal Revenue (BIR)" },
  { key: "Other process", text: "To process, prepare, sign, and submit any incidental or related applications, forms, or documents that may be necessary or required in connection with the foregoing authority, including but not limited to any compliance requirements, verifications, or clarifications with the BIR or its duly authorized representatives." },
  { key: "TIN Processing", text: "To sign, submit, pay, receive, and fill out necessary documents for the process of Taxpayer Identification Number (TIN) with the Bureau of Internal Revenue (BIR)" },
  { key: "TIN Validation", text: "To apply for, request, transact, and/or otherwise process the Taxpayer Identification Number (TIN) validation on my behalf with the Bureau of Internal Revenue (BIR)" },
  { key: "TIN Requirements", text: "To sign, submit, receive, fill out, and accomplish any and all documents and requirements in relation to TIN validation on my behalf with the Bureau of Internal Revenue (BIR)" },
  { key: "General Facilitation", text: "To apply, request, receive, sign, execute, process/submit, and facilitate documents pertaining to the above-mentioned transaction and any other legal documents that may be required." },
  { key: "Authority to Print (ATP)", text: "To sign, submit, pay, receive, and fill out necessary documents for the process of Authority to Print (ATP) with the Bureau of Internal Revenue (BIR)" },
  { key: "ATP Validation", text: "To apply for, request, transact, and/or otherwise process the Authority to Print (ATP) validation on my behalf with the Bureau of Internal Revenue (BIR)" },
  { key: "ATP Requirements", text: "To sign, submit, receive, fill out, and accomplish any and all documents and requirements in relation to Authority to Print (ATP) on my behalf with the Bureau of Internal Revenue (BIR)" }
];

export const LGU_PURPOSES = [
  { key: "Business Permit App", text: "To sign, submit, receive, fill out necessary documents for the application of business permit with the Local Government Unit (LGU)" },
  { key: "Process App", text: "To apply for, request, transact, and/or otherwise process the application of business permit with the Local Government Unit (LGU)" },
  { key: "Compliance/Clarifications", text: "To process, prepare, sign, and submit any incidental or related applications, forms, or documents that may be necessary or required in connection with the foregoing authority, including but not limited to any compliance requirements, verifications, or clarifications with the LGU or its duly authorized representatives" },
  { key: "Permit Renewal", text: "To sign, submit, pay, receive, and fill out necessary documents for the process of renewal of business permit with the Local Government Unit (LGU)" },
  { key: "Process Renewal", text: "To apply for, request, transact, and/or otherwise process the renewal of business permit with the Local Government Unit (LGU)" },
  { key: "Renewal Requirements", text: "To sign, submit, receive, fill out, and accomplish any and all documents and requirements in relation to the renewal of business permit with the Local Government Unit (LGU)" },
  { key: "General Legal Docs", text: "To apply, request, receive, sign, execute, process/submit, and facilitate documents pertaining to the above-mentioned transaction and any other legal documents that may be required." },
  { key: "Fire Safety (BFP)", text: "To apply for, request, transact, and/or otherwise process the application of Fire Safety Inspection Certificate with the Bureau of Fire Protection (BFP)" },
  { key: "BFP Requirements", text: "To sign, submit, receive, fill out, and accomplish any and all documents and requirements in relation to the application of Fire Safety Inspection Certificate with the Bureau of Fire Protection (BFP)" },
  { key: "Sanitary Permit", text: "To apply for, request, transact, and/or otherwise process the application of Sanitary Permit with the Local Government Unit (LGU)" },
  { key: "Sanitary Requirements", text: "To sign, submit, receive, fill out, and accomplish any and all documents and requirements in relation to the application of Sanitary Permit with the Local Government Unit (LGU)" },
  { key: "Occupancy Permit", text: "To apply for, request, transact, and/or otherwise process the application of Occupancy Permit with the Local Government Unit (LGU)" },
  { key: "Occupancy Requirements", text: "To sign, submit, receive, fill out, and accomplish any and all documents and requirements in relation to the application of Occupancy Permit with the Local Government Unit (LGU)" }
];

export const SSS_PURPOSES = [
  { key: "Employer Registration", text: "To sign, submit, receive, fill out, and accomplish any and all documents and requirements in relation to the Employer Registration (Form R-1), Employment Report (Form R-1A), and Specimen Signature Card (Form L-501) with the Social Security System (SSS)" },
  { key: "Employer ID/COR", text: "To apply for, request, transact, and/or otherwise process the issuance of the SSS Employer ID Number and Certificate of Registration for the purpose of legal business operation and employee coverage" },
  { key: "My.SSS Portal", text: "To sign, submit, receive, fill out, and accomplish any and all documents and requirements in relation to the creation and activation of the My.SSS Employer Portal account for the purpose of online contribution remittances and employment reporting" }
];

export const PHILHEALTH_PURPOSES = [
  { key: "ER1/ER2 Forms", text: "To sign, submit, receive, fill out, and accomplish any and all documents and requirements in relation to the Employer Data Record (ER1) and Report of Employee-Members (ER2) with the Philippine Health Insurance Corporation (PhilHealth)" },
  { key: "PEN/COR Issuance", text: "To apply for, request, transact, and/or otherwise process the issuance of the PhilHealth Employer Number (PEN) and Certificate of Registration for the purpose of mandated health insurance coverage" }
];

export const PAGIBIG_PURPOSES = [
  { key: "EDF/SSF Forms", text: "To sign, submit, receive, fill out, and accomplish any and all documents and requirements in relation to the Employer's Data Form (EDF) and Specimen Signature Form (SSF) with the Home Development Mutual Fund (Pag-IBIG Fund)" },
  { key: "Employer ID", text: "To apply for, request, transact, and/or otherwise process the issuance of the Pag-IBIG Employer ID Number for the purpose of mandated provident fund membership" }
];

export const STLAF_REPRESENTATIVES = "ATTY. CHRIS C. TAMESIS, CHESKA NICOLE SANTIAGO, SIMOUN TERRENCE ELIAS, KYZYL KATE MENDOZA, LEILA IAH CAPUA, MYRAVIE VIBAL, JOHN EMMANUEL ARELLANO, LILEAN THERESE VILLANUEVA, MATHILDE UY GUEVARA, ALVIN PANTALEON, AMIEL JOHN BAGTAS, MICHAEL MARQUEZ, or JOHN PABLO SUDARA";
